name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  salesforce-ci:
    uses: beyond-the-cloud-dev/cicd-template/.github/workflows/salesforce-ci.yml@main
    with:
      node-version: '20'
      sf-cli-version: 'latest'
      scratch-org-duration: 1
      test-level: 'RunLocalTests'
      upload-to-codecov: true
      codecov-slug: ${{ github.repository }}  # Automatically uses current repository
    secrets:
      SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
